name: Auto Generate Changesets

on:
  push:
    branches: [main]
    paths:
      - "packages/**"

permissions:
  contents: write

jobs:
  auto-changeset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Generate and commit changeset
        run: |
          # Get commit message and detect changes
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          PACKAGES=$(git diff --name-only HEAD~1 HEAD | grep "^packages/" | cut -d'/' -f2 | sort -u | tr '\n' ' ')

          if [[ -z "$PACKAGES" ]]; then
            echo "No packages changed"
            exit 0
          fi

          # Determine version bump
          if [[ $COMMIT_MSG =~ ^feat.*!:|BREAKING ]]; then
            BUMP="major"
          elif [[ $COMMIT_MSG =~ ^feat ]]; then
            BUMP="minor"
          else
            BUMP="patch"
          fi

          # Create changeset
          CHANGESET_ID="auto-$(date +%s)"
          cat > ".changeset/${CHANGESET_ID}.md" << EOF
          ---
          $(for pkg in $PACKAGES; do
            case "$pkg" in
              playwright-framework)
                echo "\"@netanelh2/playwright-framework\": $BUMP"
                ;;
              create-playwright-project)
                echo "\"@netanelh2/create-playwright-project\": $BUMP"
                ;;
              create-workflows-package)
                echo "\"@netanelh2/create-workflows-package\": $BUMP"
                ;;
            esac
          done)
          ---

          $(echo "$COMMIT_MSG" | head -n1)
          EOF

          # Commit if changeset was created
          if [ -f ".changeset/${CHANGESET_ID}.md" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add ".changeset/${CHANGESET_ID}.md"
            git commit -m "chore: add changeset [skip ci]"
            git push
            echo "✅ Changeset created and committed"
          fi
