# Simplified Auto-merge using GitHub's native auto-merge feature
# This workflow enables auto-merge and auto-approves PRs when code quality passes

name: Auto-merge with GitHub Native

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_run:
    workflows: ["Code Quality Check"]
    types: [completed]

jobs:
  notify-external-pr:
    name: Notify External PR Needs Review
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'pull_request' &&
      github.event.pull_request.draft == false &&
      github.event.pull_request.state == 'open' &&
      github.event.pull_request.user.login != 'NetanelH2'
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Notify manual review required
        uses: actions/github-script@v8
        with:
          script: |
            const pr = context.payload.pull_request;
            console.log(`🔍 External PR detected #${pr.number}: "${pr.title}"`);
            console.log(`👤 Author: ${pr.user.login}`);

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: '👋 **Thanks for your contribution!**\n\n' +
                    '🔍 **Manual review required** - This PR will be reviewed by the code owner\n' +
                    '⏳ **Code quality checks** - Will run automatically\n' +
                    '✅ **After review** - Will be merged manually by @NetanelH2\n\n' +
                    '💡 *Auto-merge is only enabled for code owner PRs for security reasons.*'
            });

            console.log('✅ Notification comment added for external PR');

  auto-approve-and-enable-merge:
    name: Auto-approve and Enable Merge
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'pull_request' &&
      github.event.pull_request.draft == false &&
      github.event.pull_request.state == 'open' &&
      github.event.pull_request.user.login == 'NetanelH2'
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Auto-approve and enable auto-merge
        uses: actions/github-script@v8
        with:
          script: |
            const pr = context.payload.pull_request;
            console.log(`🎯 Processing PR #${pr.number}: "${pr.title}"`);
            console.log(`👤 Author: ${pr.user.login}`);

            try {
              // Auto-approve the PR
              await github.rest.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                event: 'APPROVE',
                body: '🤖 Auto-approved: Will merge when code quality checks pass ✅'
              });
              
              console.log('✅ Auto-approval added');

              // Enable auto-merge
              await github.rest.pulls.enableAutoMerge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                merge_method: 'SQUASH'
              });
              
              console.log('🔄 Auto-merge enabled with squash method');

              // Add informational comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: '🤖 **Auto-merge enabled!** ⚡\n\n' +
                      '✅ **Auto-approved** - Ready to merge\n' +
                      '🔄 **Auto-merge** - Will merge automatically when all checks pass\n' +
                      '📋 **Merge method** - Squash and merge\n\n' +
                      '⏳ Waiting for code quality checks to complete...'
              });

            } catch (error) {
              console.log(`❌ Error: ${error.message}`);
              
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: `⚠️ **Auto-merge setup failed**: ${error.message}\n\n` +
                      'You may need to enable auto-merge manually or check repository settings.'
              });
            }

  merge-after-quality-check:
    name: Merge After Quality Check
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'workflow_run' &&
      github.event.workflow_run.name == 'Code Quality Check' &&
      github.event.workflow_run.conclusion == 'success'
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Find and merge PRs ready after quality check
        uses: actions/github-script@v8
        with:
          script: |
            const workflowRun = context.payload.workflow_run;
            console.log(`✅ Code Quality Check completed successfully`);
            console.log(`🔍 Head SHA: ${workflowRun.head_sha}`);

            // Find open PRs with this commit
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              per_page: 100
            });

            const matchingPRs = prs.filter(pr => pr.head.sha === workflowRun.head_sha);

            for (const pr of matchingPRs) {
              console.log(`\n🎯 Found PR #${pr.number}: "${pr.title}"`);
              console.log(`👤 Author: ${pr.user.login}`);

              // Only auto-merge PRs from code owner (NetanelH2)
              if (pr.user.login !== 'NetanelH2') {
                console.log('⏸️ Skipping auto-merge: Not from code owner. Manual review required.');
                
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: pr.number,
                  body: '✅ **Code quality checks passed!**\n\n' +
                        '👤 **Manual review required** - This PR is from an external contributor\n' +
                        '🔍 **Action needed** - Code owner review required before merge\n\n' +
                        '💡 Only PRs from @NetanelH2 are auto-merged after quality checks pass.'
                });
                continue;
              }

              console.log('✅ PR from code owner - proceeding with auto-merge');

              try {
                // Check if auto-merge is already enabled
                if (pr.auto_merge) {
                  console.log('🔄 Auto-merge already enabled - GitHub will merge automatically');
                  continue;
                }

                // If not, try to enable it and approve
                const { data: reviews } = await github.rest.pulls.listReviews({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: pr.number
                });

                const hasApproval = reviews.some(review => review.state === 'APPROVED');
                
                if (!hasApproval) {
                  await github.rest.pulls.createReview({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: pr.number,
                    event: 'APPROVE',
                    body: '🤖 Auto-approved: Code quality checks passed ✅'
                  });
                  console.log('✅ Auto-approval added');
                }

                // Try to enable auto-merge
                await github.rest.pulls.enableAutoMerge({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: pr.number,
                  merge_method: 'SQUASH'
                });
                
                console.log('🔄 Auto-merge enabled - will merge shortly');

                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: pr.number,
                  body: '✅ **Code quality checks passed!**\n\n' +
                        '🤖 Auto-merge has been enabled and this PR will be merged automatically.'
                });

              } catch (error) {
                console.log(`⚠️ Could not enable auto-merge for PR #${pr.number}: ${error.message}`);
                
                // Try direct merge as fallback
                try {
                  await github.rest.pulls.merge({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: pr.number,
                    merge_method: 'squash',
                    commit_title: `${pr.title} (#${pr.number})`,
                    commit_message: 'Auto-merged after code quality checks passed'
                  });
                  
                  console.log('🎉 Merged directly as fallback');
                  
                } catch (mergeError) {
                  console.log(`❌ Direct merge also failed: ${mergeError.message}`);
                  
                  await github.rest.issues.createComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: pr.number,
                    body: `⚠️ **Auto-merge failed**: ${mergeError.message}\n\n` +
                          '✅ Code quality checks passed but merge requires manual intervention.\n' +
                          'Please merge manually or check branch protection settings.'
                  });
                }
              }
            }
