name: Delete merged branch

on:
  pull_request:
    types: [closed]

jobs:
  delete-merged-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Delete merged branch
        uses: actions/github-script@v7
        with:
          script: |
            const branch = context.payload.pull_request.head.ref;
            const protectedBranches = ['main', 'master', 'develop']; // Add any protected branches here

            if (protectedBranches.includes(branch)) {
              console.log(`Skipping deletion of protected branch: ${branch}`);
              return;
            }

            try {
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `heads/${branch}`
              });
              console.log(`Successfully deleted branch: ${branch}`);
            } catch (error) {
              console.log(`Failed to delete branch ${branch}: ${error.message}`);
            }
