name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    name: Version and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.REPO_WORKFLOW_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm ci

      - name: Update NPM to Latest
        run: npm install -g npm@latest

      - name: Build packages
        run: npm run build --if-present

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          version: npx changeset version
          publish: npx changeset publish
          commit: 'chore: version packages'
          title: 'chore: version packages'
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_WORKFLOW_TOKEN }}

      - name: Create GitHub releases
        if: steps.changesets.outputs.published == 'true'
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.REPO_WORKFLOW_TOKEN }}
          script: |
            const publishedPackages = JSON.parse('${{ steps.changesets.outputs.publishedPackages }}');

            for (const pkg of publishedPackages) {
              const tagName = `${pkg.name}@${pkg.version}`;
              
              // Extract package directory name from scoped package name
              const pkgDir = pkg.name.replace('@netanelh2/', '');
              
              try {
                await github.rest.repos.createRelease({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  tag_name: tagName,
                  name: `${pkg.name} v${pkg.version}`,
                  body: `## What's Changed\n\nSee the full changelog at https://github.com/${context.repo.owner}/${context.repo.repo}/blob/main/packages/${pkgDir}/CHANGELOG.md`,
                  draft: false,
                  prerelease: false
                });
                console.log(`✅ Created release: ${tagName}`);
              } catch (error) {
                if (error.status === 422) {
                  console.log(`⚠️ Release ${tagName} already exists`);
                } else {
                  console.error(`❌ Failed to create release for ${tagName}: ${error.message}`);
                }
              }
            }
